version: "2"

services:
  acntech_zookeeper:
    build: .
    image: acntech/zookeeper:latest
    container_name: acntech-zookeeper
    hostname: zookeeper.acntech.internal
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"